### ISSUE TITLE
M1 Mac Executable incompatible on M1

### ISSUE THREAD

**Issue by bmckinle** [mmmorris1975/aws-runas#82] opened 2022-05-11 17:43 UTC
After downloading [this zip](https://github.com/mmmorris1975/aws-runas/releases/download/3.3.2/aws-runas-3.3.2-darwin-arm64.zip), chmod 755's the unzipped executable, and then doing file aws-runas, I receive an incompatible executable error.  I don't have the exact error as it was done on a customer's machine, but I can get the exact error if you need it.  Anyway, the m1 arm executable appears to be unrunable on an m1.  Let me know if you need the exact error.

**Comment by mmmorris1975** [comment] 2022-05-29 01:09
Closed as dupe of #84 (which has more context)

**Closed as completed by mmmorris1975** 2022-05-29 01:09 UTC
